#include "../shared.h"

struct FViewConstants {
  float4 TranslatedWorldToClip[4];
  float4 RelativeWorldToClip[4];
  float4 ClipToRelativeWorld[4];
  float4 TranslatedWorldToView[4];
  float4 ViewToTranslatedWorld[4];
  float4 TranslatedWorldToCameraView[4];
  float4 CameraViewToTranslatedWorld[4];
  float4 ViewToClip[4];
  float4 ViewToClipNoAA[4];
  float4 ClipToView[4];
  float4 ClipToTranslatedWorld[4];
  float4 SVPositionToTranslatedWorld[4];
  float4 ScreenToRelativeWorld[4];
  float4 ScreenToTranslatedWorld[4];
  float4 MobileMultiviewShadowTransform[4];
  float3 ViewOriginHigh;
  float Padding972;
  float3 ViewForward;
  float Padding988;
  float3 ViewUp;
  float Padding1004;
  float3 ViewRight;
  float Padding1020;
  float3 HMDViewNoRollUp;
  float Padding1036;
  float3 HMDViewNoRollRight;
  float Padding1052;
  float4 InvDeviceZToWorldZTransform;
  float4 ScreenPositionScaleBias;
  float3 ViewOriginLow;
  float Padding1100;
  float3 TranslatedWorldCameraOrigin;
  float Padding1116;
  float3 WorldViewOriginHigh;
  float Padding1132;
  float3 WorldViewOriginLow;
  float Padding1148;
  float3 PreViewTranslationHigh;
  float Padding1164;
  float3 PreViewTranslationLow;
  float Padding1180;
  float4 PrevViewToClip[4];
  float4 PrevClipToView[4];
  float4 PrevTranslatedWorldToClip[4];
  float4 PrevTranslatedWorldToView[4];
  float4 PrevViewToTranslatedWorld[4];
  float4 PrevTranslatedWorldToCameraView[4];
  float4 PrevCameraViewToTranslatedWorld[4];
  float3 PrevTranslatedWorldCameraOrigin;
  float Padding1644;
  float3 PrevWorldCameraOriginHigh;
  float Padding1660;
  float3 PrevWorldCameraOriginLow;
  float Padding1676;
  float3 PrevWorldViewOriginHigh;
  float Padding1692;
  float3 PrevWorldViewOriginLow;
  float Padding1708;
  float3 PrevPreViewTranslationHigh;
  float Padding1724;
  float3 PrevPreViewTranslationLow;
  float Padding1740;
  float3 ViewTilePosition;
  float Padding1756;
  float3 RelativeWorldCameraOriginTO;
  float Padding1772;
  float3 RelativeWorldViewOriginTO;
  float Padding1788;
  float3 RelativePreViewTranslationTO;
  float Padding1804;
  float3 PrevRelativeWorldCameraOriginTO;
  float Padding1820;
  float3 PrevRelativeWorldViewOriginTO;
  float Padding1836;
  float3 RelativePrevPreViewTranslationTO;
  float Padding1852;
  float4 PrevClipToRelativeWorld[4];
  float4 PrevScreenToTranslatedWorld[4];
  float4 ClipToPrevClip[4];
  float4 ClipToPrevClipWithAA[4];
  float4 TemporalAAJitter;
  float4 GlobalClippingPlane;
  float2 FieldOfViewWideAngles;
  float2 PrevFieldOfViewWideAngles;
  float4 ViewRectMin;
  float4 ViewSizeAndInvSize;
  uint4 ViewRectMinAndSize;
  float4 LightProbeSizeRatioAndInvSizeRatio;
  float4 BufferSizeAndInvSize;
  float4 BufferBilinearUVMinMax;
  float4 ScreenToViewSpace;
  float2 BufferToSceneTextureScale;
  float2 ResolutionFractionAndInv;
  int NumSceneColorMSAASamples;
  float ProjectionDepthThicknessScale;
  float PreExposure;
  float OneOverPreExposure;
  float4 DiffuseOverrideParameter;
  float4 SpecularOverrideParameter;
  float4 NormalOverrideParameter;
  float2 RoughnessOverrideParameter;
  float PrevFrameGameTime;
  float PrevFrameRealTime;
  float OutOfBoundsMask;
  float Padding2372;
  float Padding2376;
  float Padding2380;
  float3 WorldCameraMovementSinceLastFrame;
  float CullingSign;
  float NearPlane;
  float GameTime;
  float RealTime;
  float DeltaTime;
  float MaterialTextureMipBias;
  float MaterialTextureDerivativeMultiply;
  uint Random;
  uint FrameNumber;
  uint FrameCounter;
  uint StateFrameIndexMod8;
  uint StateFrameIndex;
  uint DebugViewModeMask;
  uint WorldIsPaused;
  float CameraCut;
  float UnlitViewmodeMask;
  float Padding2460;
  float4 DirectionalLightColor;
  float3 DirectionalLightDirection;
  float Padding2492;
  float4 TranslucencyLightingVolumeMin[2];
  float4 TranslucencyLightingVolumeInvSize[2];
  float4 TemporalAAParams;
  float4 CircleDOFParams;
  float DepthOfFieldSensorWidth;
  float DepthOfFieldFocalDistance;
  float DepthOfFieldScale;
  float DepthOfFieldFocalLength;
  float DepthOfFieldFocalRegion;
  float DepthOfFieldNearTransitionRegion;
  float DepthOfFieldFarTransitionRegion;
  float MotionBlurNormalizedToPixel;
  float GeneralPurposeTweak;
  float GeneralPurposeTweak2;
  float DemosaicVposOffset;
  float DecalDepthBias;
  float3 IndirectLightingColorScale;
  float Padding2652;
  float3 PrecomputedIndirectLightingColorScale;
  float Padding2668;
  float3 PrecomputedIndirectSpecularColorScale;
  float Padding2684;
  float4 AtmosphereLightDirection[2];
  float4 AtmosphereLightIlluminanceOnGroundPostTransmittance[2];
  float4 AtmosphereLightIlluminanceOuterSpace[2];
  float4 AtmosphereLightDiscLuminance[2];
  float4 AtmosphereLightDiscCosHalfApexAngle_PPTrans[2];
  float4 SkyViewLutSizeAndInvSize;
  float3 SkyCameraTranslatedWorldOrigin;
  float Padding2876;
  float4 SkyPlanetTranslatedWorldCenterAndViewHeight;
  float4 SkyViewLutReferential[4];
  float4 SkyAtmosphereSkyLuminanceFactor;
  float SkyAtmospherePresentInScene;
  float SkyAtmosphereHeightFogContribution;
  float SkyAtmosphereBottomRadiusKm;
  float SkyAtmosphereTopRadiusKm;
  float4 SkyAtmosphereCameraAerialPerspectiveVolumeSizeAndInvSize;
  float SkyAtmosphereAerialPerspectiveStartDepthKm;
  float SkyAtmosphereCameraAerialPerspectiveVolumeDepthResolution;
  float SkyAtmosphereCameraAerialPerspectiveVolumeDepthResolutionInv;
  float SkyAtmosphereCameraAerialPerspectiveVolumeDepthSliceLengthKm;
  float SkyAtmosphereCameraAerialPerspectiveVolumeDepthSliceLengthKmInv;
  float SkyAtmosphereApplyCameraAerialPerspectiveVolume;
  float Padding3032;
  float Padding3036;
  float3 NormalCurvatureToRoughnessScaleBias;
  float RenderingReflectionCaptureMask;
  float RealTimeReflectionCapture;
  float RealTimeReflectionCapturePreExposure;
  float Padding3064;
  float Padding3068;
  float4 AmbientCubemapTint;
  float AmbientCubemapIntensity;
  float SkyLightApplyPrecomputedBentNormalShadowingFlag;
  float SkyLightAffectReflectionFlag;
  float SkyLightAffectGlobalIlluminationFlag;
  float4 SkyLightColor;
  float SkyLightVolumetricScatteringIntensity;
  float Padding3124;
  float Padding3128;
  float Padding3132;
  float4 MobileSkyIrradianceEnvironmentMap[8];
  float MobilePreviewMode;
  float HMDEyePaddingOffset;
  float ReflectionCubemapMaxMip;
  float ShowDecalsMask;
  uint DistanceFieldAOSpecularOcclusionMode;
  float IndirectCapsuleSelfShadowingIntensity;
  float Padding3288;
  float Padding3292;
  float3 ReflectionEnvironmentRoughnessMixingScaleBiasAndLargestWeight;
  int StereoPassIndex;
  float4 GlobalVolumeTranslatedCenterAndExtent[6];
  float4 GlobalVolumeTranslatedWorldToUVAddAndMul[6];
  float4 GlobalDistanceFieldMipTranslatedWorldToUVScale[6];
  float4 GlobalDistanceFieldMipTranslatedWorldToUVBias[6];
  float GlobalDistanceFieldMipFactor;
  float GlobalDistanceFieldMipTransition;
  int GlobalDistanceFieldClipmapSizeInPages;
  int Padding3708;
  float3 GlobalDistanceFieldInvPageAtlasSize;
  float Padding3724;
  float3 GlobalDistanceFieldInvCoverageAtlasSize;
  float GlobalVolumeDimension;
  float GlobalVolumeTexelSize;
  float MaxGlobalDFAOConeDistance;
  uint NumGlobalSDFClipmaps;
  float CoveredExpandSurfaceScale;
  float NotCoveredExpandSurfaceScale;
  float NotCoveredMinStepScale;
  float DitheredTransparencyStepThreshold;
  float DitheredTransparencyTraceThreshold;
  int2 CursorPosition;
  float bCheckerboardSubsurfaceProfileRendering;
  float Padding3788;
  float3 VolumetricFogInvGridSize;
  float Padding3804;
  float3 VolumetricFogGridZParams;
  float Padding3820;
  float2 VolumetricFogSVPosToVolumeUV;
  float2 VolumetricFogViewGridUVToPrevViewRectUV;
  float2 VolumetricFogPrevViewGridRectUVToResourceUV;
  float2 VolumetricFogPrevUVMax;
  float2 VolumetricFogPrevUVMaxForTemporalBlend;
  float2 VolumetricFogScreenToResourceUV;
  float2 VolumetricFogUVMax;
  float VolumetricFogMaxDistance;
  float Padding3884;
  float3 VolumetricLightmapWorldToUVScale;
  float Padding3900;
  float3 VolumetricLightmapWorldToUVAdd;
  float Padding3916;
  float3 VolumetricLightmapIndirectionTextureSize;
  float VolumetricLightmapBrickSize;
  float3 VolumetricLightmapBrickTexelSize;
  float IndirectLightingCacheShowFlag;
  float EyeToPixelSpreadAngle;
  float Padding3956;
  float Padding3960;
  float Padding3964;
  float4 XRPassthroughCameraUVs[2];
  float GlobalVirtualTextureMipBias;
  uint VirtualTextureFeedbackShift;
  uint VirtualTextureFeedbackMask;
  uint VirtualTextureFeedbackStride;
  uint VirtualTextureFeedbackJitterOffset;
  uint VirtualTextureFeedbackSampleOffset;
  uint Padding4024;
  uint Padding4028;
  float4 RuntimeVirtualTextureMipLevel;
  float2 RuntimeVirtualTexturePackHeight;
  float Padding4056;
  float Padding4060;
  float4 RuntimeVirtualTextureDebugParams;
  int FarShadowStaticMeshLODBias;
  float MinRoughness;
  float Padding4088;
  float Padding4092;
  float4 HairRenderInfo;
  uint EnableSkyLight;
  uint HairRenderInfoBits;
  uint HairComponents;
  float bSubsurfacePostprocessEnabled;
  float4 SSProfilesTextureSizeAndInvSize;
  float4 SSProfilesPreIntegratedTextureSizeAndInvSize;
  float4 SpecularProfileTextureSizeAndInvSize;
  float3 PhysicsFieldClipmapCenter;
  float PhysicsFieldClipmapDistance;
  int PhysicsFieldClipmapResolution;
  int PhysicsFieldClipmapExponent;
  int PhysicsFieldClipmapCount;
  int PhysicsFieldTargetCount;
  int4 PhysicsFieldTargets[32];
  uint GPUSceneViewId;
  float ViewResolutionFraction;
  float SubSurfaceColorAsTransmittanceAtDistanceInMeters;
  float Padding4732;
  float4 TanAndInvTanHalfFOV;
  float4 PrevTanAndInvTanHalfFOV;
  float2 WorldDepthToPixelWorldRadius;
  float Padding4776;
  float Padding4780;
  float4 ScreenRayLengthMultiplier;
  float4 GlintLUTParameters0;
  float4 GlintLUTParameters1;
  int4 EnvironmentComponentsFlags;
  uint BindlessSampler_MaterialTextureBilinearWrapedSampler;
  uint Padding4852;
  uint BindlessSampler_MaterialTextureBilinearClampedSampler;
  uint Padding4860;
  uint BindlessSRV_VolumetricLightmapIndirectionTexture;
  uint Padding4868;
  uint BindlessSRV_VolumetricLightmapBrickAmbientVector;
  uint Padding4876;
  uint BindlessSRV_VolumetricLightmapBrickSHCoefficients0;
  uint Padding4884;
  uint BindlessSRV_VolumetricLightmapBrickSHCoefficients1;
  uint Padding4892;
  uint BindlessSRV_VolumetricLightmapBrickSHCoefficients2;
  uint Padding4900;
  uint BindlessSRV_VolumetricLightmapBrickSHCoefficients3;
  uint Padding4908;
  uint BindlessSRV_VolumetricLightmapBrickSHCoefficients4;
  uint Padding4916;
  uint BindlessSRV_VolumetricLightmapBrickSHCoefficients5;
  uint Padding4924;
  uint BindlessSRV_SkyBentNormalBrickTexture;
  uint Padding4932;
  uint BindlessSRV_DirectionalLightShadowingBrickTexture;
  uint Padding4940;
  uint BindlessSampler_VolumetricLightmapBrickAmbientVectorSampler;
  uint Padding4948;
  uint BindlessSampler_VolumetricLightmapTextureSampler0;
  uint Padding4956;
  uint BindlessSampler_VolumetricLightmapTextureSampler1;
  uint Padding4964;
  uint BindlessSampler_VolumetricLightmapTextureSampler2;
  uint Padding4972;
  uint BindlessSampler_VolumetricLightmapTextureSampler3;
  uint Padding4980;
  uint BindlessSampler_VolumetricLightmapTextureSampler4;
  uint Padding4988;
  uint BindlessSampler_VolumetricLightmapTextureSampler5;
  uint Padding4996;
  uint BindlessSampler_SkyBentNormalTextureSampler;
  uint Padding5004;
  uint BindlessSampler_DirectionalLightShadowingTextureSampler;
  uint Padding5012;
  uint BindlessSRV_GlobalDistanceFieldPageAtlasTexture;
  uint Padding5020;
  uint BindlessSRV_GlobalDistanceFieldCoverageAtlasTexture;
  uint Padding5028;
  uint BindlessSRV_GlobalDistanceFieldPageTableTexture;
  uint Padding5036;
  uint BindlessSRV_GlobalDistanceFieldMipTexture;
  uint Padding5044;
  uint BindlessSampler_GlobalDistanceFieldPageAtlasTextureSampler;
  uint Padding5052;
  uint BindlessSampler_GlobalDistanceFieldCoverageAtlasTextureSampler;
  uint Padding5060;
  uint BindlessSampler_GlobalDistanceFieldMipTextureSampler;
  uint Padding5068;
  uint BindlessSRV_AtmosphereTransmittanceTexture;
  uint Padding5076;
  uint BindlessSampler_AtmosphereTransmittanceTextureSampler;
  uint Padding5084;
  uint BindlessSRV_AtmosphereIrradianceTexture;
  uint Padding5092;
  uint BindlessSampler_AtmosphereIrradianceTextureSampler;
  uint Padding5100;
  uint BindlessSRV_AtmosphereInscatterTexture;
  uint Padding5108;
  uint BindlessSampler_AtmosphereInscatterTextureSampler;
  uint Padding5116;
  uint BindlessSRV_PerlinNoiseGradientTexture;
  uint Padding5124;
  uint BindlessSampler_PerlinNoiseGradientTextureSampler;
  uint Padding5132;
  uint BindlessSRV_PerlinNoise3DTexture;
  uint Padding5140;
  uint BindlessSampler_PerlinNoise3DTextureSampler;
  uint Padding5148;
  uint BindlessSRV_SobolSamplingTexture;
  uint Padding5156;
  uint BindlessSampler_SharedPointWrappedSampler;
  uint Padding5164;
  uint BindlessSampler_SharedPointClampedSampler;
  uint Padding5172;
  uint BindlessSampler_SharedBilinearWrappedSampler;
  uint Padding5180;
  uint BindlessSampler_SharedBilinearClampedSampler;
  uint Padding5188;
  uint BindlessSampler_SharedBilinearAnisoClampedSampler;
  uint Padding5196;
  uint BindlessSampler_SharedTrilinearWrappedSampler;
  uint Padding5204;
  uint BindlessSampler_SharedTrilinearClampedSampler;
  uint Padding5212;
  uint BindlessSRV_PreIntegratedBRDF;
  uint Padding5220;
  uint BindlessSampler_PreIntegratedBRDFSampler;
  uint Padding5228;
  uint BindlessSRV_SkyIrradianceEnvironmentMap;
  uint Padding5236;
  uint BindlessSRV_TransmittanceLutTexture;
  uint Padding5244;
  uint BindlessSampler_TransmittanceLutTextureSampler;
  uint Padding5252;
  uint BindlessSRV_SkyViewLutTexture;
  uint Padding5260;
  uint BindlessSampler_SkyViewLutTextureSampler;
  uint Padding5268;
  uint BindlessSRV_DistantSkyLightLutTexture;
  uint Padding5276;
  uint BindlessSampler_DistantSkyLightLutTextureSampler;
  uint Padding5284;
  uint BindlessSRV_CameraAerialPerspectiveVolume;
  uint Padding5292;
  uint BindlessSampler_CameraAerialPerspectiveVolumeSampler;
  uint Padding5300;
  uint BindlessSRV_CameraAerialPerspectiveVolumeMieOnly;
  uint Padding5308;
  uint BindlessSampler_CameraAerialPerspectiveVolumeMieOnlySampler;
  uint Padding5316;
  uint BindlessSRV_CameraAerialPerspectiveVolumeRayOnly;
  uint Padding5324;
  uint BindlessSampler_CameraAerialPerspectiveVolumeRayOnlySampler;
  uint Padding5332;
  uint BindlessSRV_HairScatteringLUTTexture;
  uint Padding5340;
  uint BindlessSampler_HairScatteringLUTSampler;
  uint Padding5348;
  uint BindlessSRV_GGXLTCMatTexture;
  uint Padding5356;
  uint BindlessSampler_GGXLTCMatSampler;
  uint Padding5364;
  uint BindlessSRV_GGXLTCAmpTexture;
  uint Padding5372;
  uint BindlessSampler_GGXLTCAmpSampler;
  uint Padding5380;
  uint BindlessSRV_SheenLTCTexture;
  uint Padding5388;
  uint BindlessSampler_SheenLTCSampler;
  uint Padding5396;
  uint bShadingEnergyConservation;
  uint bShadingEnergyPreservation;
  uint BindlessSRV_ShadingEnergyGGXSpecTexture;
  uint Padding5412;
  uint BindlessSRV_ShadingEnergyGGXGlassTexture;
  uint Padding5420;
  uint BindlessSRV_ShadingEnergyClothSpecTexture;
  uint Padding5428;
  uint BindlessSRV_ShadingEnergyDiffuseTexture;
  uint Padding5436;
  uint BindlessSampler_ShadingEnergySampler;
  uint Padding5444;
  uint BindlessSRV_GlintTexture;
  uint Padding5452;
  uint BindlessSampler_GlintSampler;
  uint Padding5460;
  uint BindlessSRV_SimpleVolumeTexture;
  uint Padding5468;
  uint BindlessSampler_SimpleVolumeTextureSampler;
  uint Padding5476;
  uint BindlessSRV_SimpleVolumeEnvTexture;
  uint Padding5484;
  uint BindlessSampler_SimpleVolumeEnvTextureSampler;
  uint Padding5492;
  uint BindlessSRV_SSProfilesTexture;
  uint Padding5500;
  uint BindlessSampler_SSProfilesSampler;
  uint Padding5508;
  uint BindlessSampler_SSProfilesTransmissionSampler;
  uint Padding5516;
  uint BindlessSRV_SSProfilesPreIntegratedTexture;
  uint Padding5524;
  uint BindlessSampler_SSProfilesPreIntegratedSampler;
  uint Padding5532;
  uint BindlessSRV_SpecularProfileTexture;
  uint Padding5540;
  uint BindlessSampler_SpecularProfileSampler;
  uint Padding5548;
  uint BindlessSRV_WaterIndirection;
  uint Padding5556;
  uint BindlessSRV_WaterData;
  uint Padding5564;
  float4 RectLightAtlasSizeAndInvSize;
  float RectLightAtlasMaxMipLevel;
  float Padding5588;
  uint BindlessSRV_RectLightAtlasTexture;
  uint Padding5596;
  uint BindlessSampler_RectLightAtlasSampler;
  uint Padding5604;
  uint Padding5608;
  uint Padding5612;
  float4 IESAtlasSizeAndInvSize;
  uint BindlessSRV_IESAtlasTexture;
  uint Padding5636;
  uint BindlessSampler_IESAtlasSampler;
  uint Padding5644;
  uint BindlessSampler_LandscapeWeightmapSampler;
  uint Padding5652;
  uint BindlessSRV_LandscapeIndirection;
  uint Padding5660;
  uint BindlessSRV_LandscapePerComponentData;
  uint Padding5668;
  uint BindlessUAV_VTFeedbackBuffer;
  uint Padding5676;
  uint BindlessSRV_PhysicsFieldClipmapBuffer;
  uint Padding5684;
  uint Padding5688;
  uint Padding5692;
  float3 TLASPreViewTranslationHigh;
  float Padding5708;
  float3 TLASPreViewTranslationLow;
};


StructuredBuffer<float4> EyeAdaptationBuffer : register(t0);

Texture2D<float4> GatherInput_SceneColor : register(t1);

Texture2D<float4> QuarterResGatherInput_SceneColor : register(t2);

RWTexture2D<float4> OutputMips_0_SceneColor : register(u0);

RWTexture2D<float4> OutputMips_1_SceneColor : register(u1);

RWTexture2D<float4> OutputMips_2_SceneColor : register(u2);

RWBuffer<uint> OutScatterDrawIndirectParameters : register(u3);

RWStructuredBuffer<float4> OutForegroundScatterDrawList : register(u4);

RWStructuredBuffer<float4> OutBackgroundScatterDrawList : register(u5);

cbuffer _RootShaderParameters : register(b0) {
  uint4 ViewportRect : packoffset(c000.x);
  float2 MaxInputBufferUV : packoffset(c001.x);
  uint MaxScatteringGroupCount : packoffset(c001.z);
  float PreProcessingToProcessingCocRadiusFactor : packoffset(c001.w);
  float MinScatteringCocRadius : packoffset(c002.x);
  float NeighborCompareMaxColor : packoffset(c002.y);
  float CocSqueeze : packoffset(c002.z);
  float4 GatherInputSize : packoffset(c005.x);
  float4 QuarterResGatherInputSize : packoffset(c007.x);
};

cbuffer View : register(b1) {
  FViewConstants View : packoffset(c000.x);
};

SamplerState D3DStaticPointClampedSampler : register(s1, space1000);

// DXIL FirstbitHi: returns bit position counting from MSB (leading zeros count)
uint firstbithigh_msb(int value) { return (value == 0) ? 0xFFFFFFFF : (31u - firstbithigh(value)); }
uint firstbithigh_msb(uint value) { return (value == 0) ? 0xFFFFFFFF : (31u - firstbithigh(value)); }

groupshared uint _global_0;
groupshared uint _global_1;
groupshared uint _global_2;
groupshared uint _global_3;

[numthreads(8, 8, 1)]
void main(
  uint3 SV_DispatchThreadID : SV_DispatchThreadID,
  uint3 SV_GroupID : SV_GroupID,
  uint3 SV_GroupThreadID : SV_GroupThreadID,
  uint SV_GroupIndex : SV_GroupIndex
) {
  int _22;
  int _27;
  int _30;
  uint _31;
  float _34;
  float _35;
  float _44;
  float _45;
  float4 _48;
  float _55;
  float _59;
  float _62;
  float _73;
  float _91;
  float _188;
  float _261;
  float _290;
  float _98;
  float _99;
  float _100;
  float _101;
  float _102;
  float _103;
  float4 _106;
  float _121;
  float _126;
  float4 _127;
  float _147;
  float4 _148;
  float4 _167;
  float _191;
  uint _192;
  bool _193;
  bool _194;
  uint _197;
  uint _202;
  int _212;
  int _218;
  float _224;
  float _232;
  uint _240;
  uint _246;
  float _253;
  uint _269;
  uint _275;
  float _282;
  float _291;
  float _292;
  float _293;
  float _294;
  int _297;
  int _298;
  int _299;
  int _300;
  float _301;
  float _304;
  int _306;
  int _307;
  int _308;
  float _309;
  int _314;
  int _315;
  float _316;
  float _320;
  float _321;
  int _323;
  float _325;
  int _327;
  float _330;
  int _332;
  float _334;
  int _336;
  float _339;
  int _341;
  float _343;
  int _345;
  int _358;
  float _360;
  int _362;
  float _365;
  float _366;
  float _367;
  float _368;
  int _370;
  int _378;
  int _379;
  int _380;
  float _381;
  float _384;
  int _386;
  int _387;
  int _388;
  float _389;
  int _394;
  int _395;
  float _396;
  float _400;
  float _401;
  int _403;
  float _405;
  int _407;
  float _408;
  int _410;
  float _412;
  int _414;
  float _415;
  int _417;
  float _419;
  int _421;
  int _430;
  float _432;
  int _434;
  float _437;
  _global_0 = 0;
  _global_1 = 0;
  GroupMemoryBarrierWithGroupSync();
  _22 = (uint)(SV_GroupIndex) >> 2;
  _27 = (_22 & 2) | ((int)(SV_GroupIndex) & 1);
  _30 = ((int)(SV_GroupIndex) & 7) | ((int)((int)(SV_GroupID.x) << 3));
  _31 = ((uint)((uint)(SV_GroupIndex) >> 3)) + ((int)(SV_GroupID.y) << 3);
  _34 = float((uint)_30) + 0.5f;
  _35 = float((uint)_31) + 0.5f;
  _44 = min((_34 * GatherInputSize.z), MaxInputBufferUV.x);
  _45 = min((_35 * GatherInputSize.w), MaxInputBufferUV.y);
  _48 = GatherInput_SceneColor.SampleLevel(D3DStaticPointClampedSampler, float2(_44, _45), 0.0f);
  _55 = EyeAdaptationBuffer[0].x;
  _59 = WaveReadLaneFirst(View.OneOverPreExposure * _55);
  _62 = PreProcessingToProcessingCocRadiusFactor * _48.w;
  _73 = abs(_62);
  _91 = (saturate(_73 - MinScatteringCocRadius) * saturate(((((_48.x + _48.z) + (_48.y * 2.0f)) * 2.5f) * _59) + -1.0f)) * saturate(min(min(_34, _35), min((float((uint)(uint)(ViewportRect.z)) - _34), (float((uint)(uint)(ViewportRect.w)) - _35))) - _73);
  [branch]
  if (_91 > 0.5f) {
    _98 = NeighborCompareMaxColor * (1.0f / _59);
    _99 = min(_48.x, _98);
    _100 = min(_48.y, _98);
    _101 = min(_48.z, _98);
    _102 = _44 - QuarterResGatherInputSize.z;
    _103 = _45 - QuarterResGatherInputSize.w;
    _106 = QuarterResGatherInput_SceneColor.SampleLevel(D3DStaticPointClampedSampler, float2(_102, _103), 0.0f);
    _121 = _59 * 1.4285714626312256f;
    _126 = min((QuarterResGatherInputSize.z + _44), MaxInputBufferUV.x);
    _127 = QuarterResGatherInput_SceneColor.SampleLevel(D3DStaticPointClampedSampler, float2(_126, _103), 0.0f);
    _147 = min((QuarterResGatherInputSize.w + _45), MaxInputBufferUV.y);
    _148 = QuarterResGatherInput_SceneColor.SampleLevel(D3DStaticPointClampedSampler, float2(_102, _147), 0.0f);
    _167 = QuarterResGatherInput_SceneColor.SampleLevel(D3DStaticPointClampedSampler, float2(_126, _147), 0.0f);
    _188 = (max(max(max(saturate((_121 * max(max((_99 - min(_106.x, _98)), 0.0f), max(max((_100 - min(_106.y, _98)), 0.0f), max((_101 - min(_106.z, _98)), 0.0f)))) + -1.0f), saturate((_121 * max(max((_99 - min(_127.x, _98)), 0.0f), max(max((_100 - min(_127.y, _98)), 0.0f), max((_101 - min(_127.z, _98)), 0.0f)))) + -1.0f)), saturate((_121 * max(max((_99 - min(_148.x, _98)), 0.0f), max(max((_100 - min(_148.y, _98)), 0.0f), max((_101 - min(_148.z, _98)), 0.0f)))) + -1.0f)), saturate((_121 * max(max((_99 - min(_167.x, _98)), 0.0f), max(max((_100 - min(_167.y, _98)), 0.0f), max((_101 - min(_167.z, _98)), 0.0f)))) + -1.0f)) * _91);
  } else {
    _188 = _91;
  }
  _191 = saturate((_188 * 2.0f) + -1.0f);
  _192 = 1 << ((((uint)(SV_GroupIndex) >> 1) & 3) | (_22 & 12));
  _193 = (_191 > 0.009999999776482582f);
  _194 = (_48.w < 0.0f);
  if (_194 && _193) {
    InterlockedOr(_global_0, _192, _197);
  }
  if (_193 && (!_194)) {
    InterlockedOr(_global_1, _192, _202);
  }
  GroupMemoryBarrierWithGroupSync();
  [branch]
  if ((int)(SV_GroupIndex) == 0) {
    [branch]
    if (!(_global_0 == 0)) {
      InterlockedAdd(OutScatterDrawIndirectParameters[1], countbits((int)(_global_0)), _212);
      _global_2 = _212;
    }
    [branch]
    if (!(_global_1 == 0)) {
      InterlockedAdd(OutScatterDrawIndirectParameters[6], countbits((int)(_global_1)), _218);
      _global_3 = _218;
    }
  }
  if ((uint)(int)(WaveGetLaneCount()) < (uint)64) {
    GroupMemoryBarrierWithGroupSync();
  }
  _224 = _48.w * _48.w;
  _232 = min(1.0f, (CocSqueeze * select(((_224 * 3.1415927410125732f) > 0.0f), (0.31830987334251404f / _224), 1.0f)));
  [branch]
  if (!((_global_0 & _192) == 0)) {
    _240 = (uint)(_global_2) + (uint)(countbits((int)(_global_0 & ((int)(_192 + (uint)(-1))))));
    [branch]
    if ((uint)_240 < (uint)MaxScatteringGroupCount) {
      _246 = _240 * 5;
      [branch]
      if (_27 == 0) {
        OutForegroundScatterDrawList[_246] = float4(_34, _35, 0.0f, 0.0f);
      }
      _253 = (_191 * select((_62 < 0.0f), 1.0f, 0.0f)) * _232;
      OutForegroundScatterDrawList[((int)(((uint)(_27 + 1)) + _246))] = float4((_253 * _48.x), (_253 * _48.y), (_253 * _48.z), _73);
      _261 = _191;
    } else {
      _261 = 0.0f;
    }
  } else {
    _261 = _191;
  }
  [branch]
  if (!((_global_1 & _192) == 0)) {
    _269 = (uint)(_global_3) + (uint)(countbits((int)(_global_1 & ((int)(_192 + (uint)(-1))))));
    [branch]
    if ((uint)_269 < (uint)MaxScatteringGroupCount) {
      _275 = _269 * 5;
      [branch]
      if (_27 == 0) {
        OutBackgroundScatterDrawList[_275] = float4(_34, _35, 0.0f, 0.0f);
      }
      _282 = (_232 * select((_62 < 0.0f), 0.0f, 1.0f)) * _261;
      OutBackgroundScatterDrawList[((int)(((uint)(_27 + 1)) + _275))] = float4((_282 * _48.x), (_282 * _48.y), (_282 * _48.z), _73);
      _290 = _261;
    } else {
      _290 = 0.0f;
    }
  } else {
    _290 = _261;
  }
  _291 = 1.0f - _290;
  // Mod: Reduce scatter subtraction aggressiveness to prevent dark voids in gather input.
  // Original fully removes scatter pixels (1 - scatterAmount), leaving black holes if
  // scatter sprite rendering has coverage gaps. Keep at least 30% of the color.
  if (InjectionToggle(TOGGLE_USE_SMOOTH_DOF)) {
    _291 = max(_291, 0.3f);
  }
  _292 = _291 * _48.x;
  _293 = _291 * _48.y;
  _294 = _291 * _48.z;
  OutputMips_0_SceneColor[int2(_30, _31)] = float4(_292, _293, _294, _48.w);
  _297 = WaveGetLaneIndex();
  _298 = _297 & 30;
  _299 = _298 | 1;
  _300 = WaveReadLaneAt(asint(_48.w),_299);
  _301 = asfloat(_300);
  _304 = select((abs(_48.w) > _301), _301, _48.w);
  _306 = _297 & 23;
  _307 = _306 | 8;
  _308 = WaveReadLaneAt(asint(_304),_307);
  _309 = asfloat(_308);
  _314 = WaveReadLaneAt(asint(select((abs(_304) > _309), _309, _304)),_298);
  _315 = WaveReadLaneAt(_314,_306);
  _316 = asfloat(_315);
  _320 = saturate(1.0f - ((_316 - _48.w) * 32.0f));
  _321 = _320 * _292;
  _323 = WaveReadLaneAt(asint(_321),_299);
  _325 = asfloat(_323) + _321;
  _327 = WaveReadLaneAt(asint(_325),_307);
  _330 = _320 * _293;
  _332 = WaveReadLaneAt(asint(_330),_299);
  _334 = asfloat(_332) + _330;
  _336 = WaveReadLaneAt(asint(_334),_307);
  _339 = _320 * _294;
  _341 = WaveReadLaneAt(asint(_339),_299);
  _343 = asfloat(_341) + _339;
  _345 = WaveReadLaneAt(asint(_343),_307);
  _358 = WaveReadLaneAt(asint(_320),_299);
  _360 = asfloat(_358) + _320;
  _362 = WaveReadLaneAt(asint(_360),_307);
  _365 = 1.0f / (asfloat(_362) + _360);
  _366 = _365 * (asfloat(_327) + _325);
  _367 = _365 * (asfloat(_336) + _334);
  _368 = _365 * (asfloat(_345) + _343);
  _370 = _31 | (int)(SV_GroupIndex);
  [branch]
  if ((_370 & 1) == 0) {
    OutputMips_1_SceneColor[int2(((uint)(_30) >> 1), ((uint)(_31) >> 1))] = float4(_366, _367, _368, _316);
  }
  _378 = _297 & 29;
  _379 = _378 | 2;
  _380 = WaveReadLaneAt(_315,_379);
  _381 = asfloat(_380);
  _384 = select((abs(_316) > _381), _381, _316);
  _386 = _297 & 15;
  _387 = _386 | 16;
  _388 = WaveReadLaneAt(asint(_384),_387);
  _389 = asfloat(_388);
  _394 = WaveReadLaneAt(asint(select((abs(_384) > _389), _389, _384)),_378);
  _395 = WaveReadLaneAt(_394,_386);
  _396 = asfloat(_395);
  _400 = saturate(1.0f - ((_396 - _316) * 16.0f));
  _401 = _400 * _366;
  _403 = WaveReadLaneAt(asint(_401),_379);
  _405 = asfloat(_403) + _401;
  _407 = WaveReadLaneAt(asint(_405),_387);
  _408 = _400 * _367;
  _410 = WaveReadLaneAt(asint(_408),_379);
  _412 = asfloat(_410) + _408;
  _414 = WaveReadLaneAt(asint(_412),_387);
  _415 = _400 * _368;
  _417 = WaveReadLaneAt(asint(_415),_379);
  _419 = asfloat(_417) + _415;
  _421 = WaveReadLaneAt(asint(_419),_387);
  _430 = WaveReadLaneAt(asint(_400),_379);
  _432 = asfloat(_430) + _400;
  _434 = WaveReadLaneAt(asint(_432),_387);
  _437 = 1.0f / (asfloat(_434) + _432);
  [branch]
  if ((_370 & 3) == 0) {
    OutputMips_2_SceneColor[int2(((uint)(_30) >> 2), ((uint)(_31) >> 2))] = float4((_437 * (asfloat(_407) + _405)), (_437 * (asfloat(_414) + _412)), (_437 * (asfloat(_421) + _419)), _396);
  }
}