#include "../shared.h"

// IS-FAST noise buffer (ByteAddressBuffer root SRV â€” avoids ReShade heap-swap corruption)
ByteAddressBuffer FASTNoiseTexture : register(t0, space50);
static const uint FAST_NOISE_W = 128u;
static const uint FAST_NOISE_H = 128u;
static const uint FAST_NOISE_SLICE_TEXELS = FAST_NOISE_W * FAST_NOISE_H;
static const uint FAST_NOISE_ELEMENT_BYTES = 8u;
static float2 FastNoiseLoad(uint x, uint y, uint slice) {
  return asfloat(FASTNoiseTexture.Load2((slice * FAST_NOISE_SLICE_TEXELS + y * FAST_NOISE_W + x) * FAST_NOISE_ELEMENT_BYTES));
}

struct FViewConstants {
  float4 TranslatedWorldToClip[4];
  float4 RelativeWorldToClip[4];
  float4 ClipToRelativeWorld[4];
  float4 TranslatedWorldToView[4];
  float4 ViewToTranslatedWorld[4];
  float4 TranslatedWorldToCameraView[4];
  float4 CameraViewToTranslatedWorld[4];
  float4 ViewToClip[4];
  float4 ViewToClipNoAA[4];
  float4 ClipToView[4];
  float4 ClipToTranslatedWorld[4];
  float4 SVPositionToTranslatedWorld[4];
  float4 ScreenToRelativeWorld[4];
  float4 ScreenToTranslatedWorld[4];
  float4 MobileMultiviewShadowTransform[4];
  float3 ViewOriginHigh;
  float Padding972;
  float3 ViewForward;
  float Padding988;
  float3 ViewUp;
  float Padding1004;
  float3 ViewRight;
  float Padding1020;
  float3 HMDViewNoRollUp;
  float Padding1036;
  float3 HMDViewNoRollRight;
  float Padding1052;
  float4 InvDeviceZToWorldZTransform;
  float4 ScreenPositionScaleBias;
  float3 ViewOriginLow;
  float Padding1100;
  float3 TranslatedWorldCameraOrigin;
  float Padding1116;
  float3 WorldViewOriginHigh;
  float Padding1132;
  float3 WorldViewOriginLow;
  float Padding1148;
  float3 PreViewTranslationHigh;
  float Padding1164;
  float3 PreViewTranslationLow;
  float Padding1180;
  float4 PrevViewToClip[4];
  float4 PrevClipToView[4];
  float4 PrevTranslatedWorldToClip[4];
  float4 PrevTranslatedWorldToView[4];
  float4 PrevViewToTranslatedWorld[4];
  float4 PrevTranslatedWorldToCameraView[4];
  float4 PrevCameraViewToTranslatedWorld[4];
  float3 PrevTranslatedWorldCameraOrigin;
  float Padding1644;
  float3 PrevWorldCameraOriginHigh;
  float Padding1660;
  float3 PrevWorldCameraOriginLow;
  float Padding1676;
  float3 PrevWorldViewOriginHigh;
  float Padding1692;
  float3 PrevWorldViewOriginLow;
  float Padding1708;
  float3 PrevPreViewTranslationHigh;
  float Padding1724;
  float3 PrevPreViewTranslationLow;
  float Padding1740;
  float3 ViewTilePosition;
  float Padding1756;
  float3 RelativeWorldCameraOriginTO;
  float Padding1772;
  float3 RelativeWorldViewOriginTO;
  float Padding1788;
  float3 RelativePreViewTranslationTO;
  float Padding1804;
  float3 PrevRelativeWorldCameraOriginTO;
  float Padding1820;
  float3 PrevRelativeWorldViewOriginTO;
  float Padding1836;
  float3 RelativePrevPreViewTranslationTO;
  float Padding1852;
  float4 PrevClipToRelativeWorld[4];
  float4 PrevScreenToTranslatedWorld[4];
  float4 ClipToPrevClip[4];
  float4 ClipToPrevClipWithAA[4];
  float4 TemporalAAJitter;
  float4 GlobalClippingPlane;
  float2 FieldOfViewWideAngles;
  float2 PrevFieldOfViewWideAngles;
  float4 ViewRectMin;
  float4 ViewSizeAndInvSize;
  uint4 ViewRectMinAndSize;
  float4 LightProbeSizeRatioAndInvSizeRatio;
  float4 BufferSizeAndInvSize;
  float4 BufferBilinearUVMinMax;
  float4 ScreenToViewSpace;
  float2 BufferToSceneTextureScale;
  float2 ResolutionFractionAndInv;
  int NumSceneColorMSAASamples;
  float ProjectionDepthThicknessScale;
  float PreExposure;
  float OneOverPreExposure;
  float4 DiffuseOverrideParameter;
  float4 SpecularOverrideParameter;
  float4 NormalOverrideParameter;
  float2 RoughnessOverrideParameter;
  float PrevFrameGameTime;
  float PrevFrameRealTime;
  float OutOfBoundsMask;
  float Padding2372;
  float Padding2376;
  float Padding2380;
  float3 WorldCameraMovementSinceLastFrame;
  float CullingSign;
  float NearPlane;
  float GameTime;
  float RealTime;
  float DeltaTime;
  float MaterialTextureMipBias;
  float MaterialTextureDerivativeMultiply;
  uint Random;
  uint FrameNumber;
  uint FrameCounter;
  uint StateFrameIndexMod8;
  uint StateFrameIndex;
  uint DebugViewModeMask;
  uint WorldIsPaused;
  float CameraCut;
  float UnlitViewmodeMask;
  float Padding2460;
  float4 DirectionalLightColor;
  float3 DirectionalLightDirection;
  float Padding2492;
  float4 TranslucencyLightingVolumeMin[2];
  float4 TranslucencyLightingVolumeInvSize[2];
  float4 TemporalAAParams;
  float4 CircleDOFParams;
  float DepthOfFieldSensorWidth;
  float DepthOfFieldFocalDistance;
  float DepthOfFieldScale;
  float DepthOfFieldFocalLength;
  float DepthOfFieldFocalRegion;
  float DepthOfFieldNearTransitionRegion;
  float DepthOfFieldFarTransitionRegion;
  float MotionBlurNormalizedToPixel;
  float GeneralPurposeTweak;
  float GeneralPurposeTweak2;
  float DemosaicVposOffset;
  float DecalDepthBias;
  float3 IndirectLightingColorScale;
  float Padding2652;
  float3 PrecomputedIndirectLightingColorScale;
  float Padding2668;
  float3 PrecomputedIndirectSpecularColorScale;
  float Padding2684;
  float4 AtmosphereLightDirection[2];
  float4 AtmosphereLightIlluminanceOnGroundPostTransmittance[2];
  float4 AtmosphereLightIlluminanceOuterSpace[2];
  float4 AtmosphereLightDiscLuminance[2];
  float4 AtmosphereLightDiscCosHalfApexAngle_PPTrans[2];
  float4 SkyViewLutSizeAndInvSize;
  float3 SkyCameraTranslatedWorldOrigin;
  float Padding2876;
  float4 SkyPlanetTranslatedWorldCenterAndViewHeight;
  float4 SkyViewLutReferential[4];
  float4 SkyAtmosphereSkyLuminanceFactor;
  float SkyAtmospherePresentInScene;
  float SkyAtmosphereHeightFogContribution;
  float SkyAtmosphereBottomRadiusKm;
  float SkyAtmosphereTopRadiusKm;
  float4 SkyAtmosphereCameraAerialPerspectiveVolumeSizeAndInvSize;
  float SkyAtmosphereAerialPerspectiveStartDepthKm;
  float SkyAtmosphereCameraAerialPerspectiveVolumeDepthResolution;
  float SkyAtmosphereCameraAerialPerspectiveVolumeDepthResolutionInv;
  float SkyAtmosphereCameraAerialPerspectiveVolumeDepthSliceLengthKm;
  float SkyAtmosphereCameraAerialPerspectiveVolumeDepthSliceLengthKmInv;
  float SkyAtmosphereApplyCameraAerialPerspectiveVolume;
  float Padding3032;
  float Padding3036;
  float3 NormalCurvatureToRoughnessScaleBias;
  float RenderingReflectionCaptureMask;
  float RealTimeReflectionCapture;
  float RealTimeReflectionCapturePreExposure;
  float Padding3064;
  float Padding3068;
  float4 AmbientCubemapTint;
  float AmbientCubemapIntensity;
  float SkyLightApplyPrecomputedBentNormalShadowingFlag;
  float SkyLightAffectReflectionFlag;
  float SkyLightAffectGlobalIlluminationFlag;
  float4 SkyLightColor;
  float SkyLightVolumetricScatteringIntensity;
  float Padding3124;
  float Padding3128;
  float Padding3132;
  float4 MobileSkyIrradianceEnvironmentMap[8];
  float MobilePreviewMode;
  float HMDEyePaddingOffset;
  float ReflectionCubemapMaxMip;
  float ShowDecalsMask;
  uint DistanceFieldAOSpecularOcclusionMode;
  float IndirectCapsuleSelfShadowingIntensity;
  float Padding3288;
  float Padding3292;
  float3 ReflectionEnvironmentRoughnessMixingScaleBiasAndLargestWeight;
  int StereoPassIndex;
  float4 GlobalVolumeTranslatedCenterAndExtent[6];
  float4 GlobalVolumeTranslatedWorldToUVAddAndMul[6];
  float4 GlobalDistanceFieldMipTranslatedWorldToUVScale[6];
  float4 GlobalDistanceFieldMipTranslatedWorldToUVBias[6];
  float GlobalDistanceFieldMipFactor;
  float GlobalDistanceFieldMipTransition;
  int GlobalDistanceFieldClipmapSizeInPages;
  int Padding3708;
  float3 GlobalDistanceFieldInvPageAtlasSize;
  float Padding3724;
  float3 GlobalDistanceFieldInvCoverageAtlasSize;
  float GlobalVolumeDimension;
  float GlobalVolumeTexelSize;
  float MaxGlobalDFAOConeDistance;
  uint NumGlobalSDFClipmaps;
  float CoveredExpandSurfaceScale;
  float NotCoveredExpandSurfaceScale;
  float NotCoveredMinStepScale;
  float DitheredTransparencyStepThreshold;
  float DitheredTransparencyTraceThreshold;
  int2 CursorPosition;
  float bCheckerboardSubsurfaceProfileRendering;
  float Padding3788;
  float3 VolumetricFogInvGridSize;
  float Padding3804;
  float3 VolumetricFogGridZParams;
  float Padding3820;
  float2 VolumetricFogSVPosToVolumeUV;
  float2 VolumetricFogViewGridUVToPrevViewRectUV;
  float2 VolumetricFogPrevViewGridRectUVToResourceUV;
  float2 VolumetricFogPrevUVMax;
  float2 VolumetricFogPrevUVMaxForTemporalBlend;
  float2 VolumetricFogScreenToResourceUV;
  float2 VolumetricFogUVMax;
  float VolumetricFogMaxDistance;
  float Padding3884;
  float3 VolumetricLightmapWorldToUVScale;
  float Padding3900;
  float3 VolumetricLightmapWorldToUVAdd;
  float Padding3916;
  float3 VolumetricLightmapIndirectionTextureSize;
  float VolumetricLightmapBrickSize;
  float3 VolumetricLightmapBrickTexelSize;
  float IndirectLightingCacheShowFlag;
  float EyeToPixelSpreadAngle;
  float Padding3956;
  float Padding3960;
  float Padding3964;
  float4 XRPassthroughCameraUVs[2];
  float GlobalVirtualTextureMipBias;
  uint VirtualTextureFeedbackShift;
  uint VirtualTextureFeedbackMask;
  uint VirtualTextureFeedbackStride;
  uint VirtualTextureFeedbackJitterOffset;
  uint VirtualTextureFeedbackSampleOffset;
  uint Padding4024;
  uint Padding4028;
  float4 RuntimeVirtualTextureMipLevel;
  float2 RuntimeVirtualTexturePackHeight;
  float Padding4056;
  float Padding4060;
  float4 RuntimeVirtualTextureDebugParams;
  int FarShadowStaticMeshLODBias;
  float MinRoughness;
  float Padding4088;
  float Padding4092;
  float4 HairRenderInfo;
  uint EnableSkyLight;
  uint HairRenderInfoBits;
  uint HairComponents;
  float bSubsurfacePostprocessEnabled;
  float4 SSProfilesTextureSizeAndInvSize;
  float4 SSProfilesPreIntegratedTextureSizeAndInvSize;
  float4 SpecularProfileTextureSizeAndInvSize;
  float3 PhysicsFieldClipmapCenter;
  float PhysicsFieldClipmapDistance;
  int PhysicsFieldClipmapResolution;
  int PhysicsFieldClipmapExponent;
  int PhysicsFieldClipmapCount;
  int PhysicsFieldTargetCount;
  int4 PhysicsFieldTargets[32];
  uint GPUSceneViewId;
  float ViewResolutionFraction;
  float SubSurfaceColorAsTransmittanceAtDistanceInMeters;
  float Padding4732;
  float4 TanAndInvTanHalfFOV;
  float4 PrevTanAndInvTanHalfFOV;
  float2 WorldDepthToPixelWorldRadius;
  float Padding4776;
  float Padding4780;
  float4 ScreenRayLengthMultiplier;
  float4 GlintLUTParameters0;
  float4 GlintLUTParameters1;
  int4 EnvironmentComponentsFlags;
  uint BindlessSampler_MaterialTextureBilinearWrapedSampler;
  uint Padding4852;
  uint BindlessSampler_MaterialTextureBilinearClampedSampler;
  uint Padding4860;
  uint BindlessSRV_VolumetricLightmapIndirectionTexture;
  uint Padding4868;
  uint BindlessSRV_VolumetricLightmapBrickAmbientVector;
  uint Padding4876;
  uint BindlessSRV_VolumetricLightmapBrickSHCoefficients0;
  uint Padding4884;
  uint BindlessSRV_VolumetricLightmapBrickSHCoefficients1;
  uint Padding4892;
  uint BindlessSRV_VolumetricLightmapBrickSHCoefficients2;
  uint Padding4900;
  uint BindlessSRV_VolumetricLightmapBrickSHCoefficients3;
  uint Padding4908;
  uint BindlessSRV_VolumetricLightmapBrickSHCoefficients4;
  uint Padding4916;
  uint BindlessSRV_VolumetricLightmapBrickSHCoefficients5;
  uint Padding4924;
  uint BindlessSRV_SkyBentNormalBrickTexture;
  uint Padding4932;
  uint BindlessSRV_DirectionalLightShadowingBrickTexture;
  uint Padding4940;
  uint BindlessSampler_VolumetricLightmapBrickAmbientVectorSampler;
  uint Padding4948;
  uint BindlessSampler_VolumetricLightmapTextureSampler0;
  uint Padding4956;
  uint BindlessSampler_VolumetricLightmapTextureSampler1;
  uint Padding4964;
  uint BindlessSampler_VolumetricLightmapTextureSampler2;
  uint Padding4972;
  uint BindlessSampler_VolumetricLightmapTextureSampler3;
  uint Padding4980;
  uint BindlessSampler_VolumetricLightmapTextureSampler4;
  uint Padding4988;
  uint BindlessSampler_VolumetricLightmapTextureSampler5;
  uint Padding4996;
  uint BindlessSampler_SkyBentNormalTextureSampler;
  uint Padding5004;
  uint BindlessSampler_DirectionalLightShadowingTextureSampler;
  uint Padding5012;
  uint BindlessSRV_GlobalDistanceFieldPageAtlasTexture;
  uint Padding5020;
  uint BindlessSRV_GlobalDistanceFieldCoverageAtlasTexture;
  uint Padding5028;
  uint BindlessSRV_GlobalDistanceFieldPageTableTexture;
  uint Padding5036;
  uint BindlessSRV_GlobalDistanceFieldMipTexture;
  uint Padding5044;
  uint BindlessSampler_GlobalDistanceFieldPageAtlasTextureSampler;
  uint Padding5052;
  uint BindlessSampler_GlobalDistanceFieldCoverageAtlasTextureSampler;
  uint Padding5060;
  uint BindlessSampler_GlobalDistanceFieldMipTextureSampler;
  uint Padding5068;
  uint BindlessSRV_AtmosphereTransmittanceTexture;
  uint Padding5076;
  uint BindlessSampler_AtmosphereTransmittanceTextureSampler;
  uint Padding5084;
  uint BindlessSRV_AtmosphereIrradianceTexture;
  uint Padding5092;
  uint BindlessSampler_AtmosphereIrradianceTextureSampler;
  uint Padding5100;
  uint BindlessSRV_AtmosphereInscatterTexture;
  uint Padding5108;
  uint BindlessSampler_AtmosphereInscatterTextureSampler;
  uint Padding5116;
  uint BindlessSRV_PerlinNoiseGradientTexture;
  uint Padding5124;
  uint BindlessSampler_PerlinNoiseGradientTextureSampler;
  uint Padding5132;
  uint BindlessSRV_PerlinNoise3DTexture;
  uint Padding5140;
  uint BindlessSampler_PerlinNoise3DTextureSampler;
  uint Padding5148;
  uint BindlessSRV_SobolSamplingTexture;
  uint Padding5156;
  uint BindlessSampler_SharedPointWrappedSampler;
  uint Padding5164;
  uint BindlessSampler_SharedPointClampedSampler;
  uint Padding5172;
  uint BindlessSampler_SharedBilinearWrappedSampler;
  uint Padding5180;
  uint BindlessSampler_SharedBilinearClampedSampler;
  uint Padding5188;
  uint BindlessSampler_SharedBilinearAnisoClampedSampler;
  uint Padding5196;
  uint BindlessSampler_SharedTrilinearWrappedSampler;
  uint Padding5204;
  uint BindlessSampler_SharedTrilinearClampedSampler;
  uint Padding5212;
  uint BindlessSRV_PreIntegratedBRDF;
  uint Padding5220;
  uint BindlessSampler_PreIntegratedBRDFSampler;
  uint Padding5228;
  uint BindlessSRV_SkyIrradianceEnvironmentMap;
  uint Padding5236;
  uint BindlessSRV_TransmittanceLutTexture;
  uint Padding5244;
  uint BindlessSampler_TransmittanceLutTextureSampler;
  uint Padding5252;
  uint BindlessSRV_SkyViewLutTexture;
  uint Padding5260;
  uint BindlessSampler_SkyViewLutTextureSampler;
  uint Padding5268;
  uint BindlessSRV_DistantSkyLightLutTexture;
  uint Padding5276;
  uint BindlessSampler_DistantSkyLightLutTextureSampler;
  uint Padding5284;
  uint BindlessSRV_CameraAerialPerspectiveVolume;
  uint Padding5292;
  uint BindlessSampler_CameraAerialPerspectiveVolumeSampler;
  uint Padding5300;
  uint BindlessSRV_CameraAerialPerspectiveVolumeMieOnly;
  uint Padding5308;
  uint BindlessSampler_CameraAerialPerspectiveVolumeMieOnlySampler;
  uint Padding5316;
  uint BindlessSRV_CameraAerialPerspectiveVolumeRayOnly;
  uint Padding5324;
  uint BindlessSampler_CameraAerialPerspectiveVolumeRayOnlySampler;
  uint Padding5332;
  uint BindlessSRV_HairScatteringLUTTexture;
  uint Padding5340;
  uint BindlessSampler_HairScatteringLUTSampler;
  uint Padding5348;
  uint BindlessSRV_GGXLTCMatTexture;
  uint Padding5356;
  uint BindlessSampler_GGXLTCMatSampler;
  uint Padding5364;
  uint BindlessSRV_GGXLTCAmpTexture;
  uint Padding5372;
  uint BindlessSampler_GGXLTCAmpSampler;
  uint Padding5380;
  uint BindlessSRV_SheenLTCTexture;
  uint Padding5388;
  uint BindlessSampler_SheenLTCSampler;
  uint Padding5396;
  uint bShadingEnergyConservation;
  uint bShadingEnergyPreservation;
  uint BindlessSRV_ShadingEnergyGGXSpecTexture;
  uint Padding5412;
  uint BindlessSRV_ShadingEnergyGGXGlassTexture;
  uint Padding5420;
  uint BindlessSRV_ShadingEnergyClothSpecTexture;
  uint Padding5428;
  uint BindlessSRV_ShadingEnergyDiffuseTexture;
  uint Padding5436;
  uint BindlessSampler_ShadingEnergySampler;
  uint Padding5444;
  uint BindlessSRV_GlintTexture;
  uint Padding5452;
  uint BindlessSampler_GlintSampler;
  uint Padding5460;
  uint BindlessSRV_SimpleVolumeTexture;
  uint Padding5468;
  uint BindlessSampler_SimpleVolumeTextureSampler;
  uint Padding5476;
  uint BindlessSRV_SimpleVolumeEnvTexture;
  uint Padding5484;
  uint BindlessSampler_SimpleVolumeEnvTextureSampler;
  uint Padding5492;
  uint BindlessSRV_SSProfilesTexture;
  uint Padding5500;
  uint BindlessSampler_SSProfilesSampler;
  uint Padding5508;
  uint BindlessSampler_SSProfilesTransmissionSampler;
  uint Padding5516;
  uint BindlessSRV_SSProfilesPreIntegratedTexture;
  uint Padding5524;
  uint BindlessSampler_SSProfilesPreIntegratedSampler;
  uint Padding5532;
  uint BindlessSRV_SpecularProfileTexture;
  uint Padding5540;
  uint BindlessSampler_SpecularProfileSampler;
  uint Padding5548;
  uint BindlessSRV_WaterIndirection;
  uint Padding5556;
  uint BindlessSRV_WaterData;
  uint Padding5564;
  float4 RectLightAtlasSizeAndInvSize;
  float RectLightAtlasMaxMipLevel;
  float Padding5588;
  uint BindlessSRV_RectLightAtlasTexture;
  uint Padding5596;
  uint BindlessSampler_RectLightAtlasSampler;
  uint Padding5604;
  uint Padding5608;
  uint Padding5612;
  float4 IESAtlasSizeAndInvSize;
  uint BindlessSRV_IESAtlasTexture;
  uint Padding5636;
  uint BindlessSampler_IESAtlasSampler;
  uint Padding5644;
  uint BindlessSampler_LandscapeWeightmapSampler;
  uint Padding5652;
  uint BindlessSRV_LandscapeIndirection;
  uint Padding5660;
  uint BindlessSRV_LandscapePerComponentData;
  uint Padding5668;
  uint BindlessUAV_VTFeedbackBuffer;
  uint Padding5676;
  uint BindlessSRV_PhysicsFieldClipmapBuffer;
  uint Padding5684;
  uint Padding5688;
  uint Padding5692;
  float3 TLASPreViewTranslationHigh;
  float Padding5708;
  float3 TLASPreViewTranslationLow;
};

struct FFogStructConstants {
  float4 ExponentialFogParameters;
  float4 ExponentialFogParameters2;
  float4 ExponentialFogColorParameter;
  float4 ExponentialFogParameters3;
  float4 SkyAtmosphereAmbientContributionColorScale;
  float4 InscatteringLightDirection;
  float4 DirectionalInscatteringColor;
  float2 SinCosInscatteringColorCubemapRotation;
  float Padding120;
  float Padding124;
  float3 FogInscatteringTextureParameters;
  float ApplyVolumetricFog;
  float VolumetricFogStartDistance;
  float VolumetricFogNearFadeInDistanceInv;
  uint BindlessSRV_FogInscatteringColorCubemap;
  uint Padding156;
  uint BindlessSampler_FogInscatteringColorSampler;
  uint Padding164;
  uint BindlessSRV_IntegratedLightScattering;
  uint Padding172;
  uint BindlessSampler_IntegratedLightScatteringSampler;
};


Texture2D<float4> View_DistantSkyLightLutTexture : register(t0);

Texture2D<float4> SceneTexturesStruct_SceneDepthTexture : register(t1);

Texture3D<float4> FogStruct_IntegratedLightScattering : register(t2);

Texture2D<float4> OcclusionTexture : register(t3);

Texture2D<float4> WaterDepthTexture : register(t4);

cbuffer _RootShaderParameters : register(b0) {
  float bOnlyOnRenderedOpaque : packoffset(c011.x);
  uint bUseWaterDepthTexture : packoffset(c011.y);
  float UpsampleJitterMultiplier : packoffset(c011.z);
  float4 WaterDepthTextureMinMaxUV : packoffset(c012.x);
  float4 OcclusionTextureMinMaxUV : packoffset(c013.x);
};

cbuffer View : register(b1) {
  FViewConstants View : packoffset(c000.x);
};

cbuffer FogStruct : register(b2) {
  FFogStructConstants FogStruct : packoffset(c000.x);
};

SamplerState View_SharedBilinearClampedSampler : register(s0);

SamplerState View_DistantSkyLightLutTextureSampler : register(s1);

SamplerState SceneTexturesStruct_PointClampSampler : register(s2);

SamplerState OcclusionSampler : register(s3);

SamplerState WaterDepthSampler : register(s4);

// DXIL FirstbitHi: returns bit position counting from MSB (leading zeros count)
uint firstbithigh_msb(int value) { return (value == 0) ? 0xFFFFFFFF : (31u - firstbithigh(value)); }
uint firstbithigh_msb(uint value) { return (value == 0) ? 0xFFFFFFFF : (31u - firstbithigh(value)); }

float4 main(
  linear float2 TEXCOORD : TEXCOORD,
  linear float3 TEXCOORD_1 : TEXCOORD1,
  precise noperspective float4 SV_Position : SV_Position
) : SV_Target {
  float4 SV_Target;
  float _61;
  float _62;
  float _250;
  float _281;
  float _282;
  float _283;
  float _284;
  float _395;
  float _396;
  float _397;
  float _409;
  float _410;
  float _411;
  float _434;
  float _435;
  float _436;
  float _437;
  float _464;
  float _465;
  float _466;
  float _467;
  float _468;
  float _485;
  float _486;
  float _487;
  float _488;
  float _64;
  float _100;
  float _101;
  float _102;
  float _103;
  uint _123;
  uint _124;
  uint _126;
  uint _128;
  uint _130;
  uint _132;
  bool _166;
  float _178;
  float _182;
  float _187;
  float _197;
  float _200;
  float _201;
  float _203;
  float _204;
  float _205;
  float _206;
  float _207;
  float _242;
  float _252;
  float _257;
  float _258;
  float _259;
  float _286;
  float _298;
  float _309;
  float4 _324;
  float _346;
  float _362;
  float _363;
  float _364;
  float _365;
  float _387;
  float _404;
  bool _421;
  float _425;
  float _426;
  float4 _452;
  float _471;
  float _476;
  bool _513;
  if (bUseWaterDepthTexture == 0) {
    _61 = (((View.InvDeviceZToWorldZTransform.x * (((float4)(SceneTexturesStruct_SceneDepthTexture.SampleLevel(SceneTexturesStruct_PointClampSampler, float2(TEXCOORD.x, TEXCOORD.y), 0.0f))).x)) + View.InvDeviceZToWorldZTransform.y) + (1.0f / ((View.InvDeviceZToWorldZTransform.z * (((float4)(SceneTexturesStruct_SceneDepthTexture.SampleLevel(SceneTexturesStruct_PointClampSampler, float2(TEXCOORD.x, TEXCOORD.y), 0.0f))).x)) - View.InvDeviceZToWorldZTransform.w)));
    _62 = (((float4)(SceneTexturesStruct_SceneDepthTexture.SampleLevel(SceneTexturesStruct_PointClampSampler, float2(TEXCOORD.x, TEXCOORD.y), 0.0f))).x);
  } else {
    _61 = (((View.InvDeviceZToWorldZTransform.x * (((float4)(WaterDepthTexture.SampleLevel(WaterDepthSampler, float2(min(max(TEXCOORD.x, WaterDepthTextureMinMaxUV.x), WaterDepthTextureMinMaxUV.z), min(max(TEXCOORD.y, WaterDepthTextureMinMaxUV.y), WaterDepthTextureMinMaxUV.w)), 0.0f))).x)) + View.InvDeviceZToWorldZTransform.y) + (1.0f / ((View.InvDeviceZToWorldZTransform.z * (((float4)(WaterDepthTexture.SampleLevel(WaterDepthSampler, float2(min(max(TEXCOORD.x, WaterDepthTextureMinMaxUV.x), WaterDepthTextureMinMaxUV.z), min(max(TEXCOORD.y, WaterDepthTextureMinMaxUV.y), WaterDepthTextureMinMaxUV.w)), 0.0f))).x)) - View.InvDeviceZToWorldZTransform.w)));
    _62 = (((float4)(WaterDepthTexture.SampleLevel(WaterDepthSampler, float2(min(max(TEXCOORD.x, WaterDepthTextureMinMaxUV.x), WaterDepthTextureMinMaxUV.z), min(max(TEXCOORD.y, WaterDepthTextureMinMaxUV.y), WaterDepthTextureMinMaxUV.w)), 0.0f))).x);
  }
  _64 = max(1.4999999853326784e-10f, _62);
  _100 = mad(_64, (View.SVPositionToTranslatedWorld[2].w), mad(SV_Position.y, (View.SVPositionToTranslatedWorld[1].w), ((View.SVPositionToTranslatedWorld[0].w) * SV_Position.x))) + (View.SVPositionToTranslatedWorld[3].w);
  _101 = (mad(_64, (View.SVPositionToTranslatedWorld[2].x), mad(SV_Position.y, (View.SVPositionToTranslatedWorld[1].x), ((View.SVPositionToTranslatedWorld[0].x) * SV_Position.x))) + (View.SVPositionToTranslatedWorld[3].x)) / _100;
  _102 = (mad(_64, (View.SVPositionToTranslatedWorld[2].y), mad(SV_Position.y, (View.SVPositionToTranslatedWorld[1].y), ((View.SVPositionToTranslatedWorld[0].y) * SV_Position.x))) + (View.SVPositionToTranslatedWorld[3].y)) / _100;
  _103 = (mad(_64, (View.SVPositionToTranslatedWorld[2].z), mad(SV_Position.y, (View.SVPositionToTranslatedWorld[1].z), ((View.SVPositionToTranslatedWorld[0].z) * SV_Position.x))) + (View.SVPositionToTranslatedWorld[3].z)) / _100;
  _123 = (int(SV_Position.y) * 1664525) + 1013904223u;
  _124 = (View.StateFrameIndexMod8 * 1664525) + 1013904223u;
  _126 = ((int(SV_Position.x) * 1664525) + 1013904223u) + (_124 * _123);
  _128 = (_126 * _124) + _123;
  _130 = (_128 * _126) + _124;
  _132 = (_130 * _128) + _126;
  _166 = (View.RenderingReflectionCaptureMask == 0.0f);
  if (!(_166) | !((View.EnvironmentComponentsFlags.x & 32) == 0)) {
    _178 = rsqrt(dot(float3(_101, _102, _103), float3(_101, _102, _103)));
    _182 = dot(float3((_178 * _101), (_178 * _102), (_178 * _103)), float3(View.ViewForward.x, View.ViewForward.y, View.ViewForward.z));
    _187 = View.VolumetricFogMaxDistance * select((_182 > 0.0010000000474974513f), (1.0f / _182), 0.0f);
    _197 = min((View.ViewOriginLow.z + View.ViewOriginHigh.z), FogStruct.ExponentialFogParameters.z);
    _200 = ((_103 - _197) + View.ViewOriginHigh.z) + View.ViewOriginLow.z;
    _201 = dot(float3(_101, _102, _200), float3(_101, _102, _200));
    _203 = rsqrt(max(_201, 9.99999993922529e-09f));
    _204 = _203 * _201;
    _205 = _203 * _101;
    _206 = _203 * _102;
    _207 = _200 * _203;
    [branch]
    if (dot(float3(View.GlobalClippingPlane.x, View.GlobalClippingPlane.y, View.GlobalClippingPlane.z), float3(1.0f, 1.0f, 1.0f)) > 0.0f) {
      _242 = (-0.0f - dot(float4(View.GlobalClippingPlane.x, View.GlobalClippingPlane.y, View.GlobalClippingPlane.z, View.GlobalClippingPlane.w), float4((((View.ViewOriginLow.x + View.ViewOriginHigh.x) + View.PreViewTranslationHigh.x) + View.PreViewTranslationLow.x), (((View.ViewOriginLow.y + View.ViewOriginHigh.y) + View.PreViewTranslationHigh.y) + View.PreViewTranslationLow.y), ((View.PreViewTranslationHigh.z + _197) + View.PreViewTranslationLow.z), 1.0f))) / dot(float3(_101, _102, _200), float3(View.GlobalClippingPlane.x, View.GlobalClippingPlane.y, View.GlobalClippingPlane.z));
      if ((int)(_242 > 0.0f) && (int)(_242 < 1.0f)) {
        _250 = max(_187, (_242 * _204));
      } else {
        _250 = _187;
      }
    } else {
      _250 = _187;
    }
    _252 = max(_250, FogStruct.ExponentialFogParameters.w);
    if (_252 > 0.0f) {
      _257 = _252 * _203;
      _258 = _257 * _200;
      _259 = _258 + _197;
      _281 = (FogStruct.ExponentialFogParameters3.x * exp2(-0.0f - max(-127.0f, ((_259 - FogStruct.ExponentialFogParameters3.y) * FogStruct.ExponentialFogParameters.y))));
      _282 = (FogStruct.ExponentialFogParameters2.z * exp2(-0.0f - max(-127.0f, ((_259 - FogStruct.ExponentialFogParameters2.w) * FogStruct.ExponentialFogParameters2.y))));
      _283 = ((1.0f - _257) * _204);
      _284 = (_200 - _258);
    } else {
      _281 = FogStruct.ExponentialFogParameters.x;
      _282 = FogStruct.ExponentialFogParameters2.x;
      _283 = _204;
      _284 = _200;
    }
    _286 = max(-127.0f, (FogStruct.ExponentialFogParameters.y * _284));
    _298 = max(-127.0f, (FogStruct.ExponentialFogParameters2.y * _284));
    _309 = (select((abs(_298) > 0.009999999776482582f), ((1.0f - exp2(-0.0f - _298)) / _298), (0.6931471824645996f - (_298 * 0.24022650718688965f))) * _282) + (select((abs(_286) > 0.009999999776482582f), ((1.0f - exp2(-0.0f - _286)) / _286), (0.6931471824645996f - (_286 * 0.24022650718688965f))) * _281);
    _324 = View_DistantSkyLightLutTexture.SampleLevel(View_DistantSkyLightLutTextureSampler, float2(0.5f, 0.5f), 0.0f);
    [branch]
    if (!(FogStruct.InscatteringLightDirection.w < 0.0f)) {
      _346 = View.SkyAtmosphereHeightFogContribution * 0.07957746833562851f;
      _362 = exp2(log2(saturate(dot(float3(_205, _206, _207), float3((View.AtmosphereLightDirection[0].x), (View.AtmosphereLightDirection[0].y), (View.AtmosphereLightDirection[0].z))))) * FogStruct.DirectionalInscatteringColor.w);
      _363 = _362 * ((_346 * (View.AtmosphereLightIlluminanceOnGroundPostTransmittance[0].x)) + FogStruct.DirectionalInscatteringColor.x);
      _364 = _362 * ((_346 * (View.AtmosphereLightIlluminanceOnGroundPostTransmittance[0].y)) + FogStruct.DirectionalInscatteringColor.y);
      _365 = _362 * ((_346 * (View.AtmosphereLightIlluminanceOnGroundPostTransmittance[0].z)) + FogStruct.DirectionalInscatteringColor.z);
      if ((View.AtmosphereLightIlluminanceOnGroundPostTransmittance[1].w) > 0.0f) {
        _387 = exp2(log2(saturate(dot(float3(_205, _206, _207), float3((View.AtmosphereLightDirection[1].x), (View.AtmosphereLightDirection[1].y), (View.AtmosphereLightDirection[1].z))))) * FogStruct.DirectionalInscatteringColor.w);
        _395 = ((_387 * ((_346 * (View.AtmosphereLightIlluminanceOnGroundPostTransmittance[1].x)) + FogStruct.DirectionalInscatteringColor.x)) + _363);
        _396 = ((_387 * ((_346 * (View.AtmosphereLightIlluminanceOnGroundPostTransmittance[1].y)) + FogStruct.DirectionalInscatteringColor.y)) + _364);
        _397 = ((_387 * ((_346 * (View.AtmosphereLightIlluminanceOnGroundPostTransmittance[1].z)) + FogStruct.DirectionalInscatteringColor.z)) + _365);
      } else {
        _395 = _363;
        _396 = _364;
        _397 = _365;
      }
      _404 = 1.0f - saturate(exp2(-0.0f - (_309 * max((_283 - FogStruct.InscatteringLightDirection.w), 0.0f))));
      _409 = (_404 * _395);
      _410 = (_404 * _396);
      _411 = (_404 * _397);
    } else {
      _409 = 0.0f;
      _410 = 0.0f;
      _411 = 0.0f;
    }
    _421 = (int)(FogStruct.ExponentialFogParameters3.w > 0.0f) && (int)(_204 > FogStruct.ExponentialFogParameters3.w);
    _425 = select(_421, 1.0f, max(saturate(exp2(-0.0f - (_283 * _309))), FogStruct.ExponentialFogColorParameter.w));
    _426 = 1.0f - _425;
    _434 = ((_426 * (((View.SkyAtmosphereHeightFogContribution * FogStruct.SkyAtmosphereAmbientContributionColorScale.x) * _324.x) + FogStruct.ExponentialFogColorParameter.x)) + select(_421, 0.0f, _409));
    _435 = ((_426 * (((View.SkyAtmosphereHeightFogContribution * FogStruct.SkyAtmosphereAmbientContributionColorScale.y) * _324.y) + FogStruct.ExponentialFogColorParameter.y)) + select(_421, 0.0f, _410));
    _436 = ((_426 * (((View.SkyAtmosphereHeightFogContribution * FogStruct.SkyAtmosphereAmbientContributionColorScale.z) * _324.z) + FogStruct.ExponentialFogColorParameter.z)) + select(_421, 0.0f, _411));
    _437 = _425;
  } else {
    _434 = 0.0f;
    _435 = 0.0f;
    _436 = 0.0f;
    _437 = 1.0f;
  }
  if (!(_166) | !((View.EnvironmentComponentsFlags.x & 32) == 0)) {
    if (FogStruct.ApplyVolumetricFog > 0.0f) {
      // Upsample jitter: offset UV when sampling the low-res fog volume at full resolution
      float _jitter_x, _jitter_y;
      if (InjectionToggle(TOGGLE_USE_ISFAST_FOG)) {
        // IS-FAST: spatiotemporally optimized noise that TAA resolves cleanly
        uint _fast_slice = View.FrameCounter % 32u;
        float2 _fast_jitter = FastNoiseLoad(
            (uint)SV_Position.x % 128u, (uint)SV_Position.y % 128u, _fast_slice);
        _jitter_x = (_fast_jitter.x * 2.0f - 1.0f) * UpsampleJitterMultiplier;
        _jitter_y = (_fast_jitter.y * 2.0f - 1.0f) * UpsampleJitterMultiplier;
      } else {
        // Original LCG hash noise
        _jitter_x = ((float((uint)((uint)((uint)(_132) >> 16))) * 3.051804378628731e-05f) + -1.0f) * UpsampleJitterMultiplier;
        _jitter_y = ((float((uint)((uint)((uint)((_132 * _130) + _128) >> 16))) * 3.051804378628731e-05f) + -1.0f) * UpsampleJitterMultiplier;
      }
      _452 = FogStruct_IntegratedLightScattering.SampleLevel(View_SharedBilinearClampedSampler, float3(min(((SV_Position.x - View.ViewRectMin.x) + _jitter_x) * View.VolumetricFogSVPosToVolumeUV.x, View.VolumetricFogUVMax.x), min(((SV_Position.y - View.ViewRectMin.y) + _jitter_y) * View.VolumetricFogSVPosToVolumeUV.y, View.VolumetricFogUVMax.y), ((View.VolumetricFogGridZParams.z * log2((View.VolumetricFogGridZParams.x * _61) + View.VolumetricFogGridZParams.y)) * View.VolumetricFogInvGridSize.z)), 0.0f);
      _464 = (View.OneOverPreExposure * _452.x);
      _465 = (View.OneOverPreExposure * _452.y);
      _466 = (View.OneOverPreExposure * _452.z);
      _467 = (_452.w + -1.0f);
      _468 = FogStruct.VolumetricFogStartDistance;
    } else {
      _464 = 0.0f;
      _465 = 0.0f;
      _466 = 0.0f;
      _467 = 0.0f;
      _468 = 0.0f;
    }
    _471 = saturate((_61 - _468) * 1e+08f);
    _476 = (_471 * _467) + 1.0f;
    _485 = ((_476 * _434) + (_471 * _464));
    _486 = ((_476 * _435) + (_471 * _465));
    _487 = ((_476 * _436) + (_471 * _466));
    _488 = (_476 * _437);
  } else {
    _485 = 0.0f;
    _486 = 0.0f;
    _487 = 0.0f;
    _488 = 1.0f;
  }
  _513 = (int)(_62 != 0.0f) || ((int)(!(bOnlyOnRenderedOpaque > 0.0f)));
  SV_Target.x = select(_513, (((((float4)(OcclusionTexture.Sample(OcclusionSampler, float2(min(max(TEXCOORD.x, OcclusionTextureMinMaxUV.x), OcclusionTextureMinMaxUV.z), min(max(TEXCOORD.y, OcclusionTextureMinMaxUV.y), OcclusionTextureMinMaxUV.w))))).x) * _485) * View.PreExposure), 0.0f);
  SV_Target.y = select(_513, (((((float4)(OcclusionTexture.Sample(OcclusionSampler, float2(min(max(TEXCOORD.x, OcclusionTextureMinMaxUV.x), OcclusionTextureMinMaxUV.z), min(max(TEXCOORD.y, OcclusionTextureMinMaxUV.y), OcclusionTextureMinMaxUV.w))))).x) * _486) * View.PreExposure), 0.0f);
  SV_Target.z = select(_513, (((((float4)(OcclusionTexture.Sample(OcclusionSampler, float2(min(max(TEXCOORD.x, OcclusionTextureMinMaxUV.x), OcclusionTextureMinMaxUV.z), min(max(TEXCOORD.y, OcclusionTextureMinMaxUV.y), OcclusionTextureMinMaxUV.w))))).x) * _487) * View.PreExposure), 0.0f);
  SV_Target.w = select(_513, _488, 1.0f);
  return SV_Target;
}